### ISSUE TITLE
Multiple files with same name or without name

### ISSUE THREAD

**Issue by nataliapc** [apoloval/mcp#1]
**case 1)** When trying to extract files from a CAS and some files have the same name and type they are overwriten by the last one.

```
ascii  | noname |   256 bytes |
bin    | noname |  7280 bytes | [0x9e98,0xbaff]:0x9e98
bin    | noname | 15112 bytes | [0x9bdc,0xd6d8]:0x9bdc
bin    | noname | 22957 bytes | [0x84d0,0xde76]:0x84d0
```

**case 2)** Trying to extract files without name from a CAS. They are ignored and don't extracted if not custom type.

```
ascii  | phant1 |   256 bytes |
bin    |        |  9744 bytes | [0xb3b0,0xd9b6]:0xcf08
bin    |        | 16072 bytes | [0x88b8,0xc772]:0x88b8
bin    |        |    40 bytes | [0xcb20,0xcb3e]:0xcb20
bin    |        | 21707 bytes | [0x88b8,0xdd7c]:0xa8d2
```

Will be nice if added support to extract files by position and rename them (when extracted or inside the CAS)

Thanks for a great project!

**Comment by apoloval** [comment]
Many thanks for using MCP! And for reporting these bugs!

I'm very busy these days. I hope to have time to fix this issue in the following weeks. Please be patient.

**Comment by apoloval** [comment]
I just released a new version 0.2.0 addressing both issues. You can either build it from master or download the binary version from the main website. 

Please check if the issue is resolved and come back to report and close the ticket.

**Comment by nataliapc** [comment]
Thanks for the quick response!

It seems they are some bug mixing CAS files names (from first and second lists):

```
C:\>mcp -l NONAMED.CAS
ascii  | noname |   256 bytes |
bin    | noname |  7280 bytes | [0x9e98,0xbaff]:0x9e98
bin    | noname | 15112 bytes | [0x9bdc,0xd6d8]:0x9bdc
bin    | noname | 22957 bytes | [0x84d0,0xde76]:0x84d0

C:\>mcp -l PHANTIS1.CAS
ascii  | phant1 |   256 bytes |
bin    |        |  9744 bytes | [0xb3b0,0xd9b6]:0xcf08
bin    |        | 16072 bytes | [0x88b8,0xc772]:0x88b8
bin    |        |    40 bytes | [0xcb20,0xcb3e]:0xcb20
bin    |        | 21707 bytes | [0x88b8,0xdd7c]:0xa8d2

C:\>mcp -x PHANTIS1.CAS
Extracting phant1.asc... Done
Extracting noname.bin... Done
Extracting noname.bin... Warning: filename "noname.bin" already exists, writing output to "noname-1.bin"... Done
Extracting noname.bin... Warning: filename "noname.bin" already exists, writing output to "noname-2.bin"... Done
Extracting noname.bin... Warning: filename "noname.bin" already exists, writing output to "noname-3.bin"... Done
```

**Comment by apoloval** [comment]
What's exactly the bug? As the warning message indicates, the first unnamed file was written to `noname.bin`, so next file is written as `noname-1.bin` and so on. What's exactly the issue there?

**Comment by nataliapc** [comment]
Sorry. It seems my mistake because the `noname.bin` filename from first CAS is the same string chosen to save empty filenames.
Maybe could be better to change `noname.bin` label when empty filenames to `________.bin`, `________-1.bin`, etc (using 8 underscores) to avoid mistakes.
What do you think about?

**Comment by apoloval** [comment]
I'm not convinced your naming scheme has big advantages over the current one. 

`noname` is a very good candidate. It has 6 bytes length, which is exactly the maximum allowed for CAS packages. It describes very well the fact that original file was blank. `mcp` command, when extracting, indicates the filename the output will be written to, so there should be no confusion on that. By contrary, an underscore file name would be inconsistent. If blank file name maps to `______`, I would expect `foo` to be mapped to `foo___`. 

Anyway. The point here is to avoid the situation when output is written to a hidden file `.bin`. And replacing blank file names to `noname` does the job. I don't see a clear benefit by changing this placeholder name.

**Comment by nataliapc** [comment]
Ok, It was just a suggestion to avoid collision cases with real `noname` labels like Nonamed game.
I understand your point too.
Anyway for future releases could be added a new command to override the default filename for empty labels (something like `-empty <label>`).
Thanks again for fixing so quickly the duplicate and empty labels issues!
