### ISSUE TITLE
Undue leading 0 when extracting custom blocks

### ISSUE THREAD

**Issue by mcolom** [apoloval/mcp#4]
Hola Álvaro,

I've tried mcp with the side B of Double Dragon, and it seems it's adding a leading 0 which should not be there.

This is what I obtain with my own tool for block 2:
00000000  cd 58 91 21 7e d8 22 28  c4 22 2a c4 3e 03 32 eb
And this is what mcp gives:
00000000  **00** cd 58 91 21 7e d8 22  28 c4 22 2a c4 3e 03 32

Perhaps I'm missing any options, but otherwise it looks like a bug.

**Comment by apoloval** [comment]
Ok, I could have a look. Could I had access to the files you are trying to package or unpackage? I should reproduce it before analyzing the problem.

**Comment by mcolom** [comment]
Hi again Álvaro,

I've checked this again, and I've realized that actually it's not a bug in your extraction, but in mine!
Your leading zero is correct.

Sorry for that... everything is correct, I'm closing the issue.

**Comment by apoloval** [comment]
Perfect! Thank you so much for using mcp and take your time to report issues!
